# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f8165090e16d478d3553fd20d654dbb2ab41925322967c1d8c44c84b7272da48f87b45834bc2cc6829ab341b03b425d2792696fed6116a4124786eb4fdd6501

test:
  secret_key_base: c390e60b63df1384d8b8b97ac1e9fbc1d96834b86d62c9d4b07588c2d88d33dee155c3ddf9e3587e81eb811fe23c3814727cb6ea1cf8679c937b60c923f94c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
